table Pedidos
	lineageTag: 3a0c3b18-fed2-4236-8c88-86e81a3519d7

	column order_id
		dataType: string
		lineageTag: b1047f16-3687-46dc-b5a3-6f3be19c2918
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 9cf05fec-fb29-4d8c-a714-45adc26f32f5
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: d19553f4-7b19-4a01-9329-07384a8e46d3
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: Long Date
		lineageTag: 357b13c2-3a5a-46ec-833d-49d62cc7e405
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		variation Variation
			isDefault
			relationship: 35e7d689-e4a2-489b-bd35-77586af38956
			defaultHierarchy: LocalDateTable_30726a0a-c817-41f8-8e6b-366ed7b5c10e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: c264673c-5252-419a-85e6-93bfba840682
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: f5d3d61e-1204-4c62-a3ca-4b8b5282fba2
			defaultHierarchy: LocalDateTable_95c6b416-ced4-4ad4-aba5-7231a699b0e1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 73c1f2c7-8da4-40b2-8443-e3a6943f3663
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: be64f272-40d4-4350-a803-b4f67c50bb53
			defaultHierarchy: LocalDateTable_c3174e41-e292-49a3-ba0f-fb338eb5e32e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 489d30fa-afa3-41e0-bb2b-bbd4ed703e30
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: 0ecba402-3fb1-4aff-b5e1-959acb865910
			defaultHierarchy: LocalDateTable_66052cc4-d8dd-4a25-bef7-bbbb89cfaf6e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 08adf611-7d0f-4a2c-ba7b-cd66e2e0431a
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: f08803da-e86f-4dad-aef5-f91f1686014d
			defaultHierarchy: LocalDateTable_a4cc7e87-94d6-4ed4-b251-3f01cda41dbc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column order_purchase_year
		dataType: string
		lineageTag: 4516f6e2-be0e-4034-b8ae-eb183e1d141e
		summarizeBy: none
		sourceColumn: order_purchase_year

		annotation SummarizationSetBy = Automatic

	column order_delivered_in_time = IF(Pedidos[order_delivered_customer_date] <= Pedidos[order_estimated_delivery_date], 1, 0)
		formatString: 0
		lineageTag: 11c49f45-9286-46ec-b884-fe4a70c79daf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column order_delivered_by_days = DATEDIFF(Pedidos[order_approved_at], Pedidos[order_delivered_customer_date], DAY)
		formatString: 0
		lineageTag: 6ac73461-9602-4a77-bc33-e083e860db03
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Pedidos = m
		mode: import
		source =
				let
				    Fonte = data,
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Name] = "olist_orders_dataset.csv")),
				    #"C:\Users\Thiago\Projetos\olist-ecommerce\data\_olist_orders_dataset csv" = #"Linhas Filtradas"{[#"Folder Path"="C:\Users\Thiago\Projetos\olist-ecommerce\data\",Name="olist_orders_dataset.csv"]}[Content],
				    #"CSV Importado" = Csv.Document(#"C:\Users\Thiago\Projetos\olist-ecommerce\data\_olist_orders_dataset csv",[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"CSV Importado", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"order_id", type text}, {"customer_id", type text}, {"order_status", type text}, {"order_purchase_timestamp", type datetime}, {"order_approved_at", type datetime}, {"order_delivered_carrier_date", type datetime}, {"order_delivered_customer_date", type datetime}, {"order_estimated_delivery_date", type datetime}}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Tipo Alterado",{{"order_status", Text.Proper, type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colocar Cada Palavra Em Maiúscula","Approved","Aprovado",Replacer.ReplaceText,{"order_status"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","Canceled","Cancelado",Replacer.ReplaceText,{"order_status"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1","Created","Criado",Replacer.ReplaceText,{"order_status"}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Valor Substituído2","Delivered","Entregue",Replacer.ReplaceText,{"order_status"}),
				    #"Valor Substituído4" = Table.ReplaceValue(#"Valor Substituído3","Invoiced","Faturado",Replacer.ReplaceText,{"order_status"}),
				    #"Valor Substituído5" = Table.ReplaceValue(#"Valor Substituído4","Processing","Processando",Replacer.ReplaceText,{"order_status"}),
				    #"Valor Substituído6" = Table.ReplaceValue(#"Valor Substituído5","Shipped","Enviado",Replacer.ReplaceText,{"order_status"}),
				    #"Valor Substituído7" = Table.ReplaceValue(#"Valor Substituído6","Unavailable","Indisponível",Replacer.ReplaceText,{"order_status"}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Valor Substituído7", "Personalizar", each Date.Year([order_purchase_timestamp])),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Personalização Adicionada",{{"Personalizar", "order_purchase_year"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

