table Reviews
	lineageTag: d3209d4b-1b45-472a-ba72-3a21a1b6c208

	column review_id
		dataType: string
		lineageTag: 6a5a7229-2de7-4089-b0e6-7a5d55f5c41d
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 9430f5cd-ff92-4852-a5cd-63304b72ad8d
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: abd8c241-7759-40ed-aed0-f131f01acdef
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_comment_title
		dataType: string
		lineageTag: fc5c9041-3baf-4685-b9f7-a635a2c222a5
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: 4741e36a-03d3-46df-9a1b-751902d4af70
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e7b62cb6-3810-4a05-ba04-e49ecfdfca01
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 91bbcc20-9d9e-45a5-a5ad-601f36ef5a13
			defaultHierarchy: LocalDateTable_cfb71588-a596-4e24-b600-1e123b3ed37d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 6f4e9e9f-2762-4e56-a9dc-4e48309d5140
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: fe5a70d6-879b-478e-b4ff-e07183e2c9bc
			defaultHierarchy: LocalDateTable_87ecb264-ed3b-4a97-8af5-46fe692884ec.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Reviews = m
		mode: import
		source =
				let
				    Fonte = data,
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Name] = "olist_order_reviews_dataset.csv")),
				    #"C:\Users\Thiago\Projetos\olist-ecommerce\data\_olist_order_reviews_dataset csv" = #"Linhas Filtradas"{[#"Folder Path"="C:\Users\Thiago\Projetos\olist-ecommerce\data\",Name="olist_order_reviews_dataset.csv"]}[Content],
				    #"CSV Importado" = Csv.Document(#"C:\Users\Thiago\Projetos\olist-ecommerce\data\_olist_order_reviews_dataset csv",[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"CSV Importado", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

