table Vendedores
	lineageTag: 429c8d0a-a55b-4231-9f16-976111f94814

	column seller_id
		dataType: string
		lineageTag: 391330d0-3464-4ab7-be9b-75ce090c8333
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column seller_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 69ea980e-d75b-4b6b-adc0-a96463882539
		summarizeBy: none
		sourceColumn: seller_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column seller_city
		dataType: string
		lineageTag: 5d773d92-afd8-46c0-80bb-cdc10b877b19
		summarizeBy: none
		sourceColumn: seller_city

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		lineageTag: 25fa43e0-1acc-4bfb-87f0-2bd9207d52bd
		summarizeBy: none
		sourceColumn: seller_state

		annotation SummarizationSetBy = Automatic

	partition Vendedores = m
		mode: import
		source =
				let
				    Fonte = data,
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Name] = "olist_sellers_dataset.csv")),
				    #"C:\Users\Thiago\Projetos\olist-ecommerce\data\_olist_sellers_dataset csv" = #"Linhas Filtradas"{[#"Folder Path"="C:\Users\Thiago\Projetos\olist-ecommerce\data\",Name="olist_sellers_dataset.csv"]}[Content],
				    #"CSV Importado" = Csv.Document(#"C:\Users\Thiago\Projetos\olist-ecommerce\data\_olist_sellers_dataset csv",[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"CSV Importado", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"seller_id", type text}, {"seller_zip_code_prefix", Int64.Type}, {"seller_city", type text}, {"seller_state", type text}}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Tipo Alterado",{{"seller_city", Text.Proper, type text}})
				in
				    #"Colocar Cada Palavra Em Maiúscula"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

